### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: jakarta.servlet.jsp.jstl.core.ConditionalTagSupport

### ISSUE THREAD

**Issue by SakthiIsaiBharathi** [jakartaee/tags#248]
Hi,

After Upgrading from 3.0.0 to 3.0.1.

org.glassfish.web
jakarta.servlet.jsp.jstl

We are getting the below issues.

Caused by: java.lang.ClassNotFoundException: jakarta.servlet.jsp.jstl.core.ConditionalTagSupport
at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]

**Comment by pzygielo** [comment]
- https://github.com/jakartaee/pages/issues/243

**Comment by hitomine** [comment]
Hi, I got same problem. 
To avoid the problem, I added this line to my build.gradle.

```
implementation 'jakarta.servlet.jsp.jstl:jakarta.servlet.jsp.jstl-api:3.0.0'
```

Dependency scope in pom.xml seems to be changed to 'provided' in 3.0.1. 

in 3.0.0

```
<dependency>
<groupId>jakarta.servlet.jsp.jstl</groupId>
<artifactId>jakarta.servlet.jsp.jstl-api</artifactId>
<version>3.0.0-RC1</version>
<scope>compile</scope>
</dependency>
```

in 3.0.1

```
<dependency>
<groupId>jakarta.servlet.jsp.jstl</groupId>
<artifactId>jakarta.servlet.jsp.jstl-api</artifactId>
<version>3.0.0</version>
<scope>provided</scope>
</dependency>
```

I don't know why this change made. (maybe bug?)

**Comment by pnicolucci** [comment]
This change looks to have been made here: https://github.com/jakartaee/tags/pull/235. I don't see why `provided` would be incorrect for the `jakarta.servlet.jsp.jstl-api` for the Jakarta Tags Implemention. In addition `provided` is used for the other APIs used by the Jakarta Tags Implementation. @SakthiIsaiBharathi are you still having an issue?
